version: "3"
services:
  php:
    image: phpdockerio/php73-cli
    container_name: psgdpr_php
    volumes:
      - ./../:/var/www/html
    working_dir: /var/www/html
    environment:
      _PS_ROOT_DIR_: /var/www/html
